version: "3.9"

services:
  backend:
    container_name: backend
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - ${APP_PORT}:${BACKEND_PORT}
    env_file: .env.dev
    environment:
      APP_PORT: int
      BACKEND_PORT: int
    networks:
      - innovorder_network
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file: .env.dev
    networks:
      - innovorder_network
    volumes:
      - postgres_db:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - innovorder_network

volumes:
  postgres_db:

networks:
  innovorder_network:
    driver: bridge
